package com.Otter.app.data.auth

import android.content.Context
import android.webkit.CookieManager
import dagger.hilt.android.qualifiers.ApplicationContext
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class CookieExporter
    @Inject
    constructor(
        @ApplicationContext private val context: Context,
    ) {
        fun exportCookiesToFile(target: CookieTarget): Result<File> {
            return runCatching {
                val cm = CookieManager.getInstance()

                // Ensure cookies are persisted from the WebView's in-memory store.
                cm.flush()

                val cookieStrings =
                    target.domains
                        .flatMap { domain ->
                            val urls =
                                buildList {
                                    add("https://$domain")
                                    if (!domain.startsWith("www.")) add("https://www.$domain")
                                }
                            urls.map { url -> cm.getCookie(url) ?: "" }
                        }
                        .filter { it.isNotBlank() }

                if (cookieStrings.isEmpty()) {
                    throw IllegalStateException("No cookies found. Please finish login and try again.")
                }

                val combinedCookieString = cookieStrings.joinToString(";")
                if (target.id == CookieTargetCatalog.TARGET_YOUTUBE) {
                    val hasAuthCookies =
                        listOf(
                            "SAPISID=",
                            "APISID=",
                            "SID=",
                            "__Secure-3PAPISID=",
                            "__Secure-3PSID=",
                        ).any { combinedCookieString.contains(it, ignoreCase = false) }

                    if (!hasAuthCookies) {
                        throw IllegalStateException(
                            "Login cookies not detected yet. Please complete login, then open youtube.com in the WebView (feed/library), wait for the page to fully load, and try again.",
                        )
                    }
                }

                val outDir = File(context.filesDir, "cookies")
                if (!outDir.exists()) outDir.mkdirs()

                val timestamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.US).format(Date())
                val outFile = File(outDir, "${target.id}_cookies_$timestamp.txt")

                val header =
                    buildString {
                        appendLine("# Netscape HTTP Cookie File")
                        appendLine("# This file was generated by Otter")
                        appendLine("#")
                    }

                val normalizedDomains =
                    target.domains
                        .map { it.removePrefix("www.").removePrefix(".") }
                        .distinct()

                val lines =
                    buildList {
                        cookieStrings.forEach { cookieString ->
                            normalizedDomains.forEach { domain ->
                                addAll(toNetscapeLines(cookieString, domain = ".$domain"))
                            }
                        }
                    }
                        .distinct()
                        .filter { it.isNotBlank() }

                if (lines.isEmpty()) {
                    throw IllegalStateException("No cookies found. Please finish login and try again.")
                }

                outFile.writeText(header + lines.joinToString(separator = "\n", postfix = "\n"))

                outFile
            }
        }

        fun exportYouTubeCookiesToFile(): Result<File> {
            return runCatching {
                val cm = CookieManager.getInstance()

                // Ensure cookies are persisted from the WebView's in-memory store.
                cm.flush()

                val cookieStrings =
                    buildList {
                        add(cm.getCookie("https://www.youtube.com") ?: "")
                        add(cm.getCookie("https://m.youtube.com") ?: "")
                        add(cm.getCookie("https://accounts.google.com") ?: "")
                        add(cm.getCookie("https://google.com") ?: "")
                        add(cm.getCookie("https://www.google.com") ?: "")
                    }.filter { it.isNotBlank() }

                val combinedCookieString = cookieStrings.joinToString(";")
                val hasAuthCookies =
                    listOf(
                        "SAPISID=",
                        "APISID=",
                        "SID=",
                        "__Secure-3PAPISID=",
                        "__Secure-3PSID=",
                    ).any { combinedCookieString.contains(it, ignoreCase = false) }

                if (!hasAuthCookies) {
                    throw IllegalStateException(
                        "Login cookies not detected yet. Please complete login, then open youtube.com in the WebView (feed/library), wait for the page to fully load, and try again.",
                    )
                }

                val outDir = File(context.filesDir, "cookies")
                if (!outDir.exists()) outDir.mkdirs()

                val timestamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.US).format(Date())
                val outFile = File(outDir, "youtube_cookies_$timestamp.txt")

                // Minimal Netscape cookie file header.
                // Note: Proper conversion from Android cookie jar to Netscape format requires
                // domain/path/expiry/httpOnly/secure attributes which aren't fully available via CookieManager.
                // We still export a best-effort file that works for many yt-dlp flows.
                val header =
                    buildString {
                        appendLine("# Netscape HTTP Cookie File")
                        appendLine("# This file was generated by Otter")
                        appendLine("#")
                    }

                val lines =
                    buildList {
                        cookieStrings.forEach { cookieString ->
                            addAll(toNetscapeLines(cookieString, domain = ".youtube.com"))
                            addAll(toNetscapeLines(cookieString, domain = ".google.com"))
                            addAll(toNetscapeLines(cookieString, domain = ".accounts.google.com"))
                        }
                    }
                        .distinct()
                        .filter { it.isNotBlank() }

                if (lines.isEmpty()) {
                    throw IllegalStateException("No cookies found. Please finish login on youtube.com and try again.")
                }

                outFile.writeText(header + lines.joinToString(separator = "\n", postfix = "\n"))

                outFile
            }
        }

        private fun toNetscapeLines(
            cookieString: String,
            domain: String,
        ): List<String> {
            if (cookieString.isBlank()) return emptyList()

            // Best-effort: convert name=value pairs to a Netscape-like tab-separated format.
            // Domain/Path/Secure/Expiry are placeholders (CookieManager doesn't expose full attributes).
            val expiry = (System.currentTimeMillis() / 1000L) + (60L * 60L * 24L * 365L * 2L) // 2 years
            val includeSubdomains = "TRUE"
            val path = "/"

            val httpOnlyLikely =
                setOf(
                    "SID",
                    "HSID",
                    "SSID",
                    "APISID",
                    "SAPISID",
                    "SIDCC",
                    "__Secure-1PSID",
                    "__Secure-3PSID",
                    "__Secure-1PAPISID",
                    "__Secure-3PAPISID",
                    "__Secure-1PSIDCC",
                    "__Secure-3PSIDCC",
                    "__Host-3PLSID",
                )

            fun isSecureCookie(name: String): Boolean {
                return name.startsWith("__Secure-") || name.startsWith("__Host-") || name in httpOnlyLikely
            }

            fun isHttpOnlyCookie(name: String): Boolean {
                return name.startsWith("__Host-") || name in httpOnlyLikely
            }

            return cookieString
                .split(';')
                .map { it.trim() }
                .filter { it.isNotEmpty() && it.contains('=') }
                .map { pair ->
                    val idx = pair.indexOf('=')
                    val name = pair.substring(0, idx)
                    val value = pair.substring(idx + 1)

                    val secure = if (isSecureCookie(name)) "TRUE" else "FALSE"
                    val outDomain = if (isHttpOnlyCookie(name)) "#HttpOnly_$domain" else domain

                    "$outDomain\t$includeSubdomains\t$path\t$secure\t$expiry\t$name\t$value"
                }
        }

        fun clearWebViewCookies(): Result<Unit> {
            return runCatching {
                val cm = CookieManager.getInstance()
                cm.removeAllCookies(null)
                cm.flush()
            }
        }
    }
