package com.Otter.app.data.repositories

import com.Otter.app.data.models.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.schabi.newpipe.extractor.InfoItem
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.stream.AudioStream
import org.schabi.newpipe.extractor.stream.StreamInfo
import org.schabi.newpipe.extractor.stream.VideoStream
import java.util.concurrent.TimeUnit
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Data class representing a resolved video stream for playback
 */
data class StreamInfoResult(
    val videoId: String,
    val title: String,
    val description: String,
    val uploaderName: String,
    val uploaderUrl: String?,
    val thumbnailUrl: String,
    val duration: Long,
    val viewCount: Long,
    val uploadDate: String?,
    val audioStreams: List<AudioStreamInfo>,
    val videoStreams: List<VideoStreamInfo>,
    val subtitles: List<SubtitleInfo>,
    val chapters: List<ChapterInfo>,
    val relatedVideos: List<RelatedVideoInfo>,
)

/**
 * Represents an audio stream with metadata
 */
data class AudioStreamInfo(
    val url: String,
    val format: String,
    val codec: String,
    val bitrate: Int,
    val sampleRate: Int,
    val quality: String,
    val mimeType: String,
    val language: String? = null,
)

/**
 * Represents a video stream with metadata
 */
data class VideoStreamInfo(
    val url: String,
    val format: String,
    val codec: String,
    val resolution: String,
    val width: Int,
    val height: Int,
    val fps: Int,
    val bitrate: Int,
    val isVideoOnly: Boolean,
    val mimeType: String,
)

/**
 * Represents a subtitle/caption track
 */
data class SubtitleInfo(
    val url: String,
    val languageCode: String,
    val languageName: String,
    val format: String,
    val isAutoGenerated: Boolean,
)

/**
 * Represents a video chapter for seeking
 */
data class ChapterInfo(
    val title: String,
    val startTimeSeconds: Int,
    val endTimeSeconds: Int,
    val thumbnailUrl: String?,
)

/**
 * Represents a related video
 */
data class RelatedVideoInfo(
    val videoId: String,
    val title: String,
    val thumbnailUrl: String,
    val uploaderName: String,
    val duration: Int,
)

/**
 * Stream resolution options for filtering
 */
enum class StreamResolution {
    SD_360P(360),
    SD_480P(480),
    HD_720P(720),
    HD_1080P(1080),
    UHD_4K(2160),
    HIGHEST(Int.MAX_VALUE),
    ;

    val maxHeight: Int

    constructor(height: Int) {
        this.maxHeight = height
    }
}

/**
 * Exception types for stream extraction errors
 */
sealed class StreamExtractionException(message: String, cause: Throwable? = null) : Exception(message, cause) {
    class NetworkError(message: String, cause: Throwable? = null) : StreamExtractionException(message, cause)

    class GeoRestricted(message: String) : StreamExtractionException(message)

    class AgeRestricted(message: String) : StreamExtractionException(message)

    class PrivateVideo(message: String) : StreamExtractionException(message)

    class VideoNotFound(message: String) : StreamExtractionException(message)

    class ContentUnavailable(message: String) : StreamExtractionException(message)

    class ExtractorError(message: String, cause: Throwable? = null) : StreamExtractionException(message, cause)

    class NoSuitableStream(message: String) : StreamExtractionException(message)
}

/**
 * Repository for extracting stream information using NewPipeExtractor.
 * Handles stream resolution, format selection, and error mapping.
 */
@Singleton
class StreamRepository
    @Inject
    constructor() {
        companion object {
            private const val CACHE_SIZE = 100
            private const val CACHE_TTL_MINUTES = 30L
        }

        // Simple LRU cache for stream info
        private val streamCache =
            object : LinkedHashMap<String, CacheEntry<StreamInfoResult>>(CACHE_SIZE, 0.75f, true) {
                override fun removeEldestEntry(eldest: MutableMap.MutableEntry<String, CacheEntry<StreamInfoResult>>?): Boolean {
                    return size > CACHE_SIZE
                }
            }

        private data class CacheEntry<T>(
            val data: T,
            val timestamp: Long = System.currentTimeMillis(),
        )

        private fun isCacheValid(timestamp: Long): Boolean {
            val age = System.currentTimeMillis() - timestamp
            return age < TimeUnit.MINUTES.toMillis(CACHE_TTL_MINUTES)
        }

        /**
         * Extract stream information for a video URL with user preferences applied.
         *
         * @param videoUrl The video URL to extract
         * @param settings User's streaming preferences
         * @return Result containing StreamInfoResult or StreamExtractionException
         */
        suspend fun extractStreamInfo(
            videoUrl: String,
            settings: AppSettings,
        ): Result<StreamInfoResult> =
            withContext(Dispatchers.IO) {
                runCatching {
                    // Check cache first
                    val cached = streamCache[videoUrl]
                    if (cached != null && isCacheValid(cached.timestamp)) {
                        return@withContext Result.success(cached.data)
                    }

                    val service = NewPipe.getServiceByUrl(videoUrl)
                    val extractor = service.getStreamExtractor(videoUrl)
                    extractor.fetchPage()

                    val streamInfo = StreamInfo.getInfo(extractor)

                    val result =
                        StreamInfoResult(
                            videoId = extractor.id,
                            title = streamInfo.name ?: "",
                            description = streamInfo.description?.content ?: "",
                            uploaderName = streamInfo.uploaderName ?: "",
                            uploaderUrl = streamInfo.uploaderUrl,
                            thumbnailUrl = streamInfo.thumbnails?.firstOrNull()?.url ?: "",
                            duration = streamInfo.duration,
                            viewCount = streamInfo.viewCount,
                            uploadDate = streamInfo.uploadDate?.offsetDateTime()?.toString(),
                            audioStreams = streamInfo.audioStreams?.map { it.toAudioStreamInfo() } ?: emptyList(),
                            videoStreams =
                                (
                                    (streamInfo.videoStreams ?: emptyList()) +
                                        (streamInfo.videoOnlyStreams ?: emptyList())
                                ).map { it.toVideoStreamInfo() },
                            subtitles = streamInfo.subtitles?.map { it.toSubtitleInfo() } ?: emptyList(),
                            chapters = streamInfo.streamSegments?.map { it.toChapterInfo() } ?: emptyList(),
                            relatedVideos =
                                streamInfo.relatedItems?.filterIsInstance<InfoItem>()?.take(
                                    10,
                                )?.map { it.toRelatedVideoInfo() } ?: emptyList(),
                        )

                    // Cache the result
                    streamCache[videoUrl] = CacheEntry(result)

                    Result.success(result)
                }.getOrElse { error ->
                    Result.failure(mapExtractionError(error, videoUrl))
                }
            }

        /**
         * Select the best video stream based on user preferences
         */
        fun selectBestVideoStream(
            streams: List<VideoStreamInfo>,
            settings: AppSettings,
        ): VideoStreamInfo? {
            val preferredStreams = streams.filterNot { it.isVideoOnly }.ifEmpty { streams }

            val qualityHeight =
                when (settings.streamingQuality) {
                    StreamingQuality.AUTO -> Int.MAX_VALUE
                    StreamingQuality.SD_360P -> 360
                    StreamingQuality.SD_480P -> 480
                    StreamingQuality.HD_720P -> 720
                    StreamingQuality.HD_1080P -> 1080
                    StreamingQuality.UHD_4K -> 2160
                    StreamingQuality.HIGHEST -> Int.MAX_VALUE
                }

            // Filter by data saver if enabled
            var filteredStreams =
                if (settings.streamingDataSaver) {
                    preferredStreams.filter { it.height <= 480 }
                } else {
                    preferredStreams
                }

            // Filter by quality preference (Int.MAX_VALUE means no limit)
            filteredStreams =
                if (qualityHeight == Int.MAX_VALUE) {
                    filteredStreams // No height limit, keep all streams
                } else {
                    filteredStreams.filter { it.height <= qualityHeight }
                }.ifEmpty { preferredStreams } // Fallback to all streams if no match

            // Filter by codec preference
            filteredStreams =
                when (settings.preferredCodec) {
                    PreferredCodec.AUTO -> filteredStreams
                    PreferredCodec.AV1 ->
                        filteredStreams.filter {
                            it.codec.contains(
                                "av01",
                                ignoreCase = true,
                            ) || it.codec.contains("av1", ignoreCase = true)
                        }
                    PreferredCodec.VP9 ->
                        filteredStreams.filter {
                            it.codec.contains(
                                "vp9",
                                ignoreCase = true,
                            ) || it.codec.contains("vp09", ignoreCase = true)
                        }
                    PreferredCodec.H264 ->
                        filteredStreams.filter {
                            it.codec.contains("avc", ignoreCase = true) || it.codec.contains("h264", ignoreCase = true)
                        }
                }.ifEmpty { filteredStreams } // Fallback if codec preference not available

            // Sort by resolution (descending), then by bitrate (descending)
            return filteredStreams
                .sortedWith(
                    compareByDescending<VideoStreamInfo> { it.height }
                        .thenByDescending { it.bitrate },
                )
                .firstOrNull()
        }

        /**
         * Select the best audio stream based on quality and format preference
         */
        fun selectBestAudioStream(
            streams: List<AudioStreamInfo>,
            settings: AppSettings,
        ): AudioStreamInfo? {
            // Sort by bitrate (descending)
            return streams
                .sortedByDescending { it.bitrate }
                .firstOrNull()
        }

        /**
         * Get stream URL for direct playback with preferences applied
         */
        suspend fun getPlaybackUrl(
            videoUrl: String,
            settings: AppSettings,
        ): Result<String> =
            withContext(Dispatchers.IO) {
                extractStreamInfo(videoUrl, settings).mapCatching { info ->
                    if (settings.streamingAudioOnly) {
                        val audioStream =
                            selectBestAudioStream(info.audioStreams, settings)
                                ?: throw StreamExtractionException.NoSuitableStream("No audio stream available")
                        audioStream.url
                    } else {
                        val videoStream =
                            selectBestVideoStream(info.videoStreams, settings)
                                ?: throw StreamExtractionException.NoSuitableStream("No suitable video stream available")
                        videoStream.url
                    }
                }
            }

        /**
         * Clear the stream cache
         */
        fun clearCache() {
            streamCache.clear()
        }

        /**
         * Remove a specific entry from cache
         */
        fun invalidateCache(videoUrl: String) {
            streamCache.remove(videoUrl)
        }

        /**
         * Map NewPipeExtractor exceptions to our domain exceptions
         */
        private fun mapExtractionError(
            error: Throwable,
            url: String,
        ): StreamExtractionException {
            val message = error.message ?: "Unknown error"

            return when {
                error is org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException -> {
                    when {
                        message.contains("geo", ignoreCase = true) ->
                            StreamExtractionException.GeoRestricted("This content is not available in your region")
                        message.contains("age", ignoreCase = true) || message.contains("age-restricted", ignoreCase = true) ->
                            StreamExtractionException.AgeRestricted("This content is age-restricted")
                        message.contains("private", ignoreCase = true) ->
                            StreamExtractionException.PrivateVideo("This video is private")
                        message.contains("not found", ignoreCase = true) || message.contains("does not exist", ignoreCase = true) ->
                            StreamExtractionException.VideoNotFound("Video not found")
                        else ->
                            StreamExtractionException.ContentUnavailable("Content unavailable: $message")
                    }
                }
                error is org.schabi.newpipe.extractor.exceptions.ReCaptchaException ->
                    StreamExtractionException.NetworkError("ReCaptcha challenge required", error)
                error is java.net.UnknownHostException ||
                    error is java.net.SocketTimeoutException ||
                    error is java.io.IOException ->
                    StreamExtractionException.NetworkError("Network error: ${error.message}", error)
                else ->
                    StreamExtractionException.ExtractorError("Extraction failed: ${error.message}", error)
            }
        }
    }

// Extension functions to map NewPipe types to our domain types

private fun AudioStream.toAudioStreamInfo(): AudioStreamInfo {
    return AudioStreamInfo(
        url = this.content ?: "",
        format = this.format?.name ?: "UNKNOWN",
        codec = this.codec ?: "",
        bitrate = this.bitrate,
        sampleRate = 0, // NewPipe doesn't expose this directly
        quality = this.quality ?: "",
        mimeType = this.format?.mimeType ?: "",
        language = this.audioLocale?.displayLanguage ?: this.audioTrackName,
    )
}

private fun VideoStream.toVideoStreamInfo(): VideoStreamInfo {
    return VideoStreamInfo(
        url = this.content ?: "",
        format = this.format?.name ?: "UNKNOWN",
        codec = this.codec ?: "",
        resolution = this.resolution ?: "",
        width = this.width,
        height = this.height,
        fps = this.fps,
        bitrate = this.bitrate,
        isVideoOnly = this.isVideoOnly,
        mimeType = this.format?.mimeType ?: "",
    )
}

private fun org.schabi.newpipe.extractor.stream.SubtitlesStream.toSubtitleInfo(): SubtitleInfo {
    return SubtitleInfo(
        url = this.content ?: "",
        languageCode = this.languageTag ?: "",
        languageName = this.displayLanguageName ?: "",
        format = this.format?.name ?: "",
        isAutoGenerated = this.isAutoGenerated,
    )
}

private fun org.schabi.newpipe.extractor.stream.StreamSegment.toChapterInfo(): ChapterInfo {
    return ChapterInfo(
        title = this.title ?: "",
        startTimeSeconds = this.startTimeSeconds,
        endTimeSeconds = -1, // NewPipe doesn't provide end time directly
        thumbnailUrl = this.previewUrl,
    )
}

private fun InfoItem.toRelatedVideoInfo(): RelatedVideoInfo {
    return RelatedVideoInfo(
        videoId = this.url ?: "",
        title = this.name ?: "",
        thumbnailUrl = this.thumbnails?.firstOrNull()?.url ?: "",
        uploaderName = "", // InfoItem doesn't have uploaderName
        duration = 0,
    )
}
